apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicdkiu-ingress
  namespace: asetyadi          # change if your namespace is different
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: asetyadi.57.158.184.247.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cicdkiu-svc
                port:
                  number: 80
